### ISSUE TITLE
issueベースの開発_レビュー依頼

### ISSUE THREAD

**Issue by nago77777** [nago77777/I-ll-buy-that-#25]
### 実装予定の機能
- [ ] ログイン機能
  - [ ] LINE連携機能
  - [ ] X連携機能
- [ ] 診断機能
- [ ] カレンダー機能
- [ ] 診断結果作成機能
- [ ] 診断結果投稿機能
- [ ] 診断結果編集機能
- [ ] 診断結果削除機能
- [ ] ログイン時・結果削除時のダイアログ機能
- [ ] SNS共有機能
- [ ] 診断結果検索機能
- [ ] いいね機能
- [ ] プロフィール変更機能
- [ ] LINEリマインド機能

### 必要なページ

- [ ] トップページ
- [ ] ログインページ
- [ ] 診断情報入力ページ
- [ ] 診断結果出力ページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] みんなの診断結果一覧ページ
- [ ] 自身の診断結果一覧ページ
- [ ] 自身の診断詳細ページ
- [ ] 自身の診断編集ページ
- [ ] プロフィールページ
- [ ] プロフィール編集ページ

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
projectsを見た印象ですが、やや重ためもしくは初めての実装部分にストーリーポイント5を付けているように見受けられました。ストーリーポイント1,2くらいになるくらい、細かくissue化すると、どの部分は分かっていて、どの部分は不鮮明になっているのかが可視化されますし、ポイントの消化が容易になり、進捗を感じながら開発を進められるかと思うので、一度見直し＆手を加えることを進言します。

**Comment by nago77777** [comment]
レビューありがとうございます。
ストーリーポイント5以上だった、デプロイ関連・LINEリマインド機能・診断機能実装を細分化し最高ストーリーポイントが3になるよう各種変更しました。ご確認よろしくお願いいたします。

**Comment by ky0613** [comment]
対応ありがとうございます！
概ね良いかと思います！LGTMです！
